engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
    config:
      strings:
      - "@todo"
ratings:
  paths:
  - **.js
  - **.jsx
  - lib/**/*
  - client2/**/*
exclude_paths:
- "legacy_client"
- "**/public"
- "place-csvs-here"
