engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
    config:
      strings:
      - "@todo"
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "lib/**/*"
  - "client/**/*"
exclude_paths:
- "legacy_client"
- "**/public"
- "place-csvs-here"
